import { AnchorProvider, BN, Program, Wallet } from "@coral-xyz/anchor";
import {
	getOrCreateAssociatedTokenAccount,
	TOKEN_2022_PROGRAM_ID,
} from "@solana/spl-token";
import { Connection, Keypair, PublicKey, Transaction } from "@solana/web3.js";
import {
	deriveMinterQuota,
	deriveRolesConfig,
	deriveStablecoinState,
} from "./client/accounts";
import { ComplianceModule } from "./compliance/ComplianceModule";
import { OracleModule } from "./oracle/OracleModule";
import { SSS_1 } from "./presets";
import { PrivacyModule } from "./privacy/PrivacyModule";
import {
	CreateOptions,
	MinterQuotaInfo,
	MinterUpdateOptions,
	RolesStatus,
	RolesUpdate,
	StablecoinStatus,
} from "./types";

// IDL auto-generated by Anchor build.
// eslint-disable-next-line @typescript-eslint/no-var-requires
const IDL = require("./idl/sss_token.json");

/** Default transfer hook program ID from the SSS project's declare_id. */
export const DEFAULT_TRANSFER_HOOK_PROGRAM_ID = new PublicKey(
	"HPksBobjquMqBfnCgpqBQDkomJ4HmGB1AbvJnemNBEig",
);

export class SolanaStablecoin {
	private program: Program;
	private connection: Connection;
	private authority: Keypair;

	public readonly mint: PublicKey;
	public readonly programId: PublicKey;
	public readonly stateAddress: PublicKey;
	public readonly rolesAddress: PublicKey;
	public readonly compliance: ComplianceModule;
	public readonly privacy: PrivacyModule;
	public readonly oracle: OracleModule;

	private constructor(
		program: Program,
		connection: Connection,
		authority: Keypair,
		mint: PublicKey,
		transferHookProgramId?: PublicKey,
		oracleProgramId?: PublicKey,
	) {
		this.program = program;
		this.connection = connection;
		this.authority = authority;
		this.mint = mint;
		this.programId = program.programId;
		const [statePda] = deriveStablecoinState(mint, program.programId);
		const [rolesPda] = deriveRolesConfig(mint, program.programId);
		this.stateAddress = statePda;
		this.rolesAddress = rolesPda;
		this.compliance = new ComplianceModule(
			program,
			connection,
			mint,
			authority,
			transferHookProgramId,
		);
		this.privacy = new PrivacyModule(program, mint, authority);
		this.oracle = new OracleModule(
			connection,
			mint,
			authority,
			oracleProgramId,
		);
	}

	// ── Factory ────────────────────────────────────────────────────────────────

	/**
	 * Create a new stablecoin from a preset or custom config.
	 *
	 * @example
	 * // SSS-1 preset
	 * const stable = await SolanaStablecoin.create(connection, {
	 *   preset: Presets.SSS_1,
	 *   name: 'My Dollar',
	 *   symbol: 'MYDOL',
	 *   decimals: 6,
	 *   authority: adminKeypair,
	 * });
	 *
	 * // SSS-2 preset
	 * const compliant = await SolanaStablecoin.create(connection, {
	 *   preset: Presets.SSS_2,
	 *   name: 'Compliant USD',
	 *   symbol: 'CUSD',
	 *   authority: adminKeypair,
	 *   transferHookProgramId: hookProgramId,
	 * });
	 *
	 * // Custom config (no preset)
	 * const custom = await SolanaStablecoin.create(connection, {
	 *   name: 'Custom',
	 *   symbol: 'CUST',
	 *   enablePermanentDelegate: true,
	 *   enableConfidentialTransfers: true,
	 *   authority: adminKeypair,
	 * });
	 */
	static async create(
		connection: Connection,
		options: CreateOptions & {
			authority: Keypair;
			mintKeypair?: Keypair;
			programId?: PublicKey;
			oracleProgramId?: PublicKey;
		},
	): Promise<{ stablecoin: SolanaStablecoin; signature: string }> {
		const wallet = new Wallet(options.authority);
		const provider: AnchorProvider = new AnchorProvider(connection, wallet, {
			commitment: "confirmed",
		});
		const program = new Program(IDL as any, provider);

		const preset = options.preset ?? SSS_1;
		const ext = options.extensions ?? {};

		const mintKeypair = options.mintKeypair ?? Keypair.generate();

		// Resolve config: explicit options > extensions > preset
		const enableMintCloseAuthority = options.enableMintCloseAuthority ?? false; // Default false for Metaplex compatibility
		const enablePermanentDelegate =
			options.enablePermanentDelegate ??
			ext.permanentDelegate ??
			preset.enablePermanentDelegate;
		const enableTransferHook =
			options.enableTransferHook ??
			ext.transferHook ??
			preset.enableTransferHook;
		const defaultAccountFrozen =
			options.defaultAccountFrozen ??
			ext.defaultAccountFrozen ??
			preset.defaultAccountFrozen;
		const enableConfidentialTransfers =
			options.enableConfidentialTransfers ?? preset.enableConfidentialTransfers;
		const confidentialTransferAutoApprove =
			options.confidentialTransferAutoApprove ??
			preset.confidentialTransferAutoApprove;

		// Convert auditor pubkey to number array for Anchor serialization
		const auditorElgamalPubkey = options.auditorElGamalPubkey
			? Array.from(options.auditorElGamalPubkey)
			: null;

		const config = {
			name: options.name,
			symbol: options.symbol,
			uri: options.uri ?? "",
			decimals: options.decimals ?? 6,
			enableMintCloseAuthority,
			enablePermanentDelegate,
			enableTransferHook,
			defaultAccountFrozen,
			transferHookProgramId: options.transferHookProgramId ?? null,
			enableConfidentialTransfers,
			confidentialTransferAutoApprove,
			auditorElgamalPubkey: auditorElgamalPubkey,
		};

		const signature = await (program.methods as any)
			.initialize(config)
			.accounts({
				authority: options.authority.publicKey,
				mint: mintKeypair.publicKey,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.signers([mintKeypair])
			.rpc();

		const hookProgramId = enableTransferHook
			? (options.transferHookProgramId ?? DEFAULT_TRANSFER_HOOK_PROGRAM_ID)
			: undefined;

		return {
			stablecoin: new SolanaStablecoin(
				program,
				connection,
				options.authority,
				mintKeypair.publicKey,
				hookProgramId,
				options.oracleProgramId,
			),
			signature,
		};
	}

	/**
	 * Load an existing stablecoin by mint address.
	 *
	 * If the mint has a transfer hook enabled, the SDK will default to the
	 * project's transfer hook program ID. Pass `options.transferHookProgramId`
	 * to override.
	 */
	static async load(
		connection: Connection,
		mint: PublicKey,
		authority: Keypair,
		options?: {
			programId?: PublicKey;
			transferHookProgramId?: PublicKey;
			oracleProgramId?: PublicKey;
		},
	): Promise<SolanaStablecoin> {
		const id =
			options?.programId ?? new PublicKey(IDL.address ?? IDL.metadata?.address);
		const wallet = new Wallet(authority);
		const provider: AnchorProvider = new AnchorProvider(connection, wallet, {
			commitment: "confirmed",
		});
		const program = new Program(IDL as any, provider);

		// Auto-detect transfer hook: read state and default to project hook program
		let hookProgramId = options?.transferHookProgramId;
		if (!hookProgramId) {
			try {
				const [statePda] = deriveStablecoinState(mint, id);
				const state = await (program.account as any).stablecoinState.fetch(
					statePda,
				);
				if (state.enableTransferHook) {
					hookProgramId = DEFAULT_TRANSFER_HOOK_PROGRAM_ID;
				}
			} catch {
				// State not readable — skip hook auto-detection
			}
		}

		return new SolanaStablecoin(
			program,
			connection,
			authority,
			mint,
			hookProgramId,
			options?.oracleProgramId,
		);
	}

	// ── Administrative Operations ──────────────────────────────────────────────

	/**
	 * Initialize Metaplex Token Metadata for wallet and explorer display.
	 *
	 * This creates a Metaplex metadata PDA that makes your token visible in all
	 * Solana wallets (Phantom, Solflare, etc.) and explorers (Solscan, Solana FM).
	 *
	 * IMPORTANT: The mint keypair must sign this transaction. This is a Metaplex
	 * requirement for Token-2022 mints with PDA authority.
	 *
	 * NOTE: Metaplex metadata is incompatible with MintCloseAuthority. If you
	 * initialized your token with enableMintCloseAuthority: true, this will fail.
	 *
	 * @param options - Metadata configuration
	 * @param options.name - Token name (max 32 bytes, e.g., "My Stablecoin")
	 * @param options.symbol - Token symbol (max 10 bytes, e.g., "MYUSD")
	 * @param options.uri - Metadata JSON URI (Arweave, IPFS, or HTTPS)
	 * @param options.sellerFeeBasisPoints - Royalty fee in basis points (default: 0, stablecoins don't need royalties)
	 * @param mintKeypair - The mint keypair (required to sign)
	 *
	 * @returns The Metaplex metadata PDA address
	 *
	 * @example
	 * const metadataPda = await stablecoin.initializeMetaplexMetadata({
	 *   name: "My Stablecoin",
	 *   symbol: "MYUSD",
	 *   uri: "https://arweave.net/...",
	 *   sellerFeeBasisPoints: 0,
	 * }, mintKeypair);
	 *
	 * console.log("Metadata created at:", metadataPda.toBase58());
	 * console.log("Your token will now display in wallets!");
	 */
	async initializeMetaplexMetadata(
		options: {
			name: string;
			symbol: string;
			uri: string;
			sellerFeeBasisPoints?: number;
		},
		mintKeypair: Keypair,
	): Promise<PublicKey> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);

		// Derive Metaplex metadata PDA
		const METAPLEX_PROGRAM_ID = new PublicKey(
			"metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s",
		);
		const [metadataPda] = PublicKey.findProgramAddressSync(
			[
				Buffer.from("metadata"),
				METAPLEX_PROGRAM_ID.toBuffer(),
				this.mint.toBuffer(),
			],
			METAPLEX_PROGRAM_ID,
		);

		await (this.program.methods as any)
			.metaplexMetadata({
				name: options.name,
				symbol: options.symbol,
				uri: options.uri,
			})
			.accounts({
				authority: this.authority.publicKey,
				mint: this.mint,
				stablecoinState: statePda,
				metadata: metadataPda,
				tokenMetadataProgram: METAPLEX_PROGRAM_ID,
				sysvarInstructions: new PublicKey(
					"Sysvar1nstructions1111111111111111111111111",
				),
			})
			.signers([this.authority, mintKeypair])
			.rpc();

		return metadataPda;
	}

	// ── Core Operations ────────────────────────────────────────────────────────

	/**
	 * Mint tokens to a recipient. Creates the recipient's ATA if needed.
	 * The minter must have an active MinterQuota PDA with sufficient quota.
	 */
	async mintTokens(options: {
		recipient: PublicKey;
		amount: bigint;
		minter?: Keypair;
	}): Promise<string> {
		const minter = options.minter ?? this.authority;

		const ata = await getOrCreateAssociatedTokenAccount(
			this.connection,
			this.authority,
			this.mint,
			options.recipient,
			false,
			"confirmed",
			{},
			TOKEN_2022_PROGRAM_ID,
		);

		const [minterQuotaPda] = deriveMinterQuota(
			this.mint,
			minter.publicKey,
			this.program.programId,
		);
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.mint(new BN(options.amount.toString()))
			.accounts({
				minter: minter.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				minterQuota: minterQuotaPda,
				mint: this.mint,
				recipientTokenAccount: ata.address,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.signers([minter])
			.rpc();
	}

	/**
	 * Burn tokens from a token account.
	 * The burner must be the token account owner and hold the burner role.
	 */
	async burn(options: {
		fromTokenAccount: PublicKey;
		amount: bigint;
		burner?: Keypair;
	}): Promise<string> {
		const burner = options.burner ?? this.authority;
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.burn(new BN(options.amount.toString()))
			.accounts({
				burner: burner.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				mint: this.mint,
				fromTokenAccount: options.fromTokenAccount,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.signers([burner])
			.rpc();
	}

	/**
	 * Prepare a transaction for minting tokens.
	 * Returns a Transaction object that can be signed by an external wallet.
	 */
	async prepareMintTransaction(options: {
		recipient: PublicKey;
		amount: bigint;
		minter: PublicKey;
	}): Promise<Transaction> {
		const ata = await getOrCreateAssociatedTokenAccount(
			this.connection,
			this.authority,
			this.mint,
			options.recipient,
			false,
			"confirmed",
			{},
			TOKEN_2022_PROGRAM_ID,
		);

		const [minterQuotaPda] = deriveMinterQuota(
			this.mint,
			options.minter,
			this.program.programId,
		);
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.mint(new BN(options.amount.toString()))
			.accounts({
				minter: options.minter,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				minterQuota: minterQuotaPda,
				mint: this.mint,
				recipientTokenAccount: ata.address,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.transaction();
	}

	/**
	 * Prepare a transaction for burning tokens.
	 * Returns a Transaction object that can be signed by an external wallet.
	 */
	async prepareBurnTransaction(options: {
		fromTokenAccount: PublicKey;
		amount: bigint;
		burner: PublicKey;
	}): Promise<Transaction> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.burn(new BN(options.amount.toString()))
			.accounts({
				burner: options.burner,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				mint: this.mint,
				fromTokenAccount: options.fromTokenAccount,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.transaction();
	}

	/** Freeze a token account. Requires master or pauser role. */
	async freeze(tokenAccount: PublicKey): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.freezeAccount()
			.accounts({
				authority: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				mint: this.mint,
				targetAccount: tokenAccount,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.signers([this.authority])
			.rpc();
	}

	/** Thaw (unfreeze) a token account. Requires master or pauser role. */
	async thaw(tokenAccount: PublicKey): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.thawAccount()
			.accounts({
				authority: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				mint: this.mint,
				targetAccount: tokenAccount,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.signers([this.authority])
			.rpc();
	}

	/**
	 * Pause minting and burning globally.
	 * Fails with AlreadyPaused if already paused.
	 */
	async pause(reason?: string): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.pause(reason ?? null)
			.accounts({
				pauser: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
			})
			.signers([this.authority])
			.rpc();
	}

	/**
	 * Unpause minting and burning.
	 * Fails with NotPaused if not currently paused.
	 */
	async unpause(): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.unpause()
			.accounts({
				pauser: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
			})
			.signers([this.authority])
			.rpc();
	}

	/**
	 * Permanently close the mint and reclaim all rent.
	 * Supply must be zero. This is irreversible.
	 * Closes: Token-2022 mint, StablecoinState PDA, RolesConfig PDA.
	 *
	 * After calling this, the SDK instance is effectively dead —
	 * any subsequent calls will fail because the state accounts are closed.
	 */
	async closeMint(): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.closeMint()
			.accounts({
				authority: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				mint: this.mint,
				tokenProgram: TOKEN_2022_PROGRAM_ID,
			})
			.signers([this.authority])
			.rpc();
	}

	// ── Role Management ────────────────────────────────────────────────────────

	/**
	 * Update role assignments. Only the master authority can call this.
	 * Only provided fields are updated; omitted fields keep their current value.
	 */
	async updateRoles(updates: RolesUpdate): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.updateRoles({
				burner: updates.burner ?? null,
				pauser: updates.pauser ?? null,
				blacklister: updates.blacklister ?? null,
				seizer: updates.seizer ?? null,
			})
			.accounts({
				authority: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
			})
			.signers([this.authority])
			.rpc();
	}

	/**
	 * Initiate master authority transfer (step 1 of 2).
	 * The current master calls this to propose a new master.
	 * The new master must call `acceptAuthority()` to complete the transfer.
	 */
	async transferAuthority(newMaster: PublicKey): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.transferAuthority(newMaster)
			.accounts({
				caller: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
			})
			.signers([this.authority])
			.rpc();
	}

	/**
	 * Accept pending master authority transfer (step 2 of 2).
	 * The pending master calls this to finalize the transfer.
	 */
	async acceptAuthority(): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);

		return (this.program.methods as any)
			.transferAuthority(null)
			.accounts({
				caller: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
			})
			.signers([this.authority])
			.rpc();
	}

	// ── Minter Management ──────────────────────────────────────────────────────

	/**
	 * Register a new minter with a quota.
	 * Creates the MinterQuota PDA. Requires master authority.
	 * @param minter - The minter's wallet address.
	 * @param quota - Maximum tokens this minter can mint (0 = unlimited).
	 */
	async addMinter(minter: PublicKey, quota: bigint): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);
		const [quotaPda] = deriveMinterQuota(
			this.mint,
			minter,
			this.program.programId,
		);

		return (this.program.methods as any)
			.addMinter(new BN(quota.toString()))
			.accounts({
				authority: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				minter,
				minterQuota: quotaPda,
			})
			.signers([this.authority])
			.rpc();
	}

	/**
	 * Remove a minter. Closes the MinterQuota PDA and reclaims rent.
	 * Requires master authority.
	 */
	async removeMinter(minter: PublicKey): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);
		const [quotaPda] = deriveMinterQuota(
			this.mint,
			minter,
			this.program.programId,
		);

		return (this.program.methods as any)
			.removeMinter()
			.accounts({
				authority: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				minter,
				minterQuota: quotaPda,
			})
			.signers([this.authority])
			.rpc();
	}

	/**
	 * Update a minter's quota, active status, or reset minted counter.
	 * Requires master authority.
	 */
	async updateMinter(options: MinterUpdateOptions): Promise<string> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);
		const [quotaPda] = deriveMinterQuota(
			this.mint,
			options.minter,
			this.program.programId,
		);

		return (this.program.methods as any)
			.updateMinter(
				new BN(options.quota.toString()),
				options.active,
				options.resetMinted ?? false,
			)
			.accounts({
				authority: this.authority.publicKey,
				stablecoinState: statePda,
				rolesConfig: rolesPda,
				minter: options.minter,
				minterQuota: quotaPda,
			})
			.signers([this.authority])
			.rpc();
	}

	// ── Queries ────────────────────────────────────────────────────────────────

	/** Fetch the stablecoin status from the StablecoinState PDA. */
	async getStatus(): Promise<StablecoinStatus> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const state = await (this.program.account as any).stablecoinState.fetch(
			statePda,
		);

		return {
			version: state.version,
			mint: state.mint,
			name: state.name,
			symbol: state.symbol,
			decimals: state.decimals,
			uri: state.uri,
			paused: state.paused,
			totalSupply: BigInt(state.totalSupply.toString()),
			enablePermanentDelegate: state.enablePermanentDelegate,
			enableTransferHook: state.enableTransferHook,
			defaultAccountFrozen: state.defaultAccountFrozen,
			enableConfidentialTransfers: state.enableConfidentialTransfers,
			confidentialTransferAutoApprove: state.confidentialTransferAutoApprove,
		};
	}

	/**
	 * Fetch token metadata from the StablecoinState PDA.
	 *
	 * Note: On-mint Token-2022 metadata is not populated due to Solana CPI limitations.
	 * This method reads metadata from the StablecoinState PDA, which is the canonical
	 * source of truth for token information.
	 *
	 * @returns Token metadata (name, symbol, URI, decimals)
	 *
	 * @example
	 * const metadata = await stablecoin.getMetadata();
	 * console.log(`${metadata.name} (${metadata.symbol})`);
	 * console.log(`Decimals: ${metadata.decimals}`);
	 * console.log(`URI: ${metadata.uri}`);
	 */
	async getMetadata(): Promise<{
		name: string;
		symbol: string;
		uri: string;
		decimals: number;
	}> {
		const [statePda] = deriveStablecoinState(this.mint, this.program.programId);
		const state = await (this.program.account as any).stablecoinState.fetch(
			statePda,
		);

		return {
			name: state.name,
			symbol: state.symbol,
			uri: state.uri,
			decimals: state.decimals,
		};
	}

	/** Fetch current role assignments from the RolesConfig PDA. */
	async getRoles(): Promise<RolesStatus> {
		const [rolesPda] = deriveRolesConfig(this.mint, this.program.programId);
		const roles = await (this.program.account as any).rolesConfig.fetch(
			rolesPda,
		);

		return {
			masterAuthority: roles.masterAuthority,
			pendingMaster: roles.pendingMaster ?? null,
			burner: roles.burner,
			pauser: roles.pauser,
			blacklister: roles.blacklister,
			seizer: roles.seizer,
		};
	}

	/**
	 * Fetch all MinterQuota PDAs for this mint.
	 * Uses Anchor's getProgramAccounts with a memcmp filter on the mint field.
	 */
	async getMinters(): Promise<MinterQuotaInfo[]> {
		const accounts = await (this.program.account as any).minterQuota.all([
			{
				memcmp: {
					offset: 8, // skip 8-byte discriminator; first field is `mint`
					bytes: this.mint.toBase58(),
				},
			},
		]);

		return accounts.map((a: any) => ({
			mint: a.account.mint,
			minter: a.account.minter,
			quota: BigInt(a.account.quota.toString()),
			minted: BigInt(a.account.minted.toString()),
			active: a.account.active,
		}));
	}

	/**
	 * Get the canonical total supply by reading directly from the mint account.
	 * This is the source of truth, even if tokens were burned directly via
	 * Token-2022 bypassing the sss-token program.
	 */
	async getTotalSupply(): Promise<bigint> {
		const info = await this.connection.getTokenSupply(this.mint);
		return BigInt(info.value.amount);
	}
}
