[fuzz.metrics]
enabled = true


[[fuzz.programs]]
address = "F8wwXWp8JUKVrDPwFCpG2NrheV3X7KKatoDuiYeBigkf"
program = "../target/deploy/transfer_hook.so"

[[fuzz.programs]]
address = "7gw6jAKSZx4mueRHcT8kxtjWen9X53NJdKHrXNUwUQrd"
program = "../target/deploy/sss_oracle.so"

[[fuzz.programs]]
address = "EsfnG79GeuaxGxnttbJ2kHYRs8CwP5RNNMbr6a3MiZaK"
program = "../target/deploy/sss_token.so"
 